# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Modern-Ops-Devsecops'
    backendAzureRmResourceGroupName: 'application-resource-group'
    
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Modern-Ops-Devsecops'
    
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Modern-Ops-Devsecops'


# - task: TerraformTaskV3@3
#   inputs:
#     provider: 'azurerm'
#     command: 'destroy'
#     environmentServiceNameAzureRM: 'Modern-Ops-Devsecops'

