apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-application
  template:
    metadata:
      labels:
        app: demo-application
    spec:
      containers:
      - name: demo-application
        image: demoappcontainerregistery.azurecr.io/shobitdemoapplication:0.0.1
        ports:
        - containerPort: 80


