apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-application
  template:
    metadata:
      labels:
        app: demo-application
    spec:
      containers:
      - name: demo-application
        image: demoappcontainerregistery.azurecr.io/shobitdemoapplication:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-application
spec:
  selector:
    app: demo-application
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
